drop table "MARTYNIUKP"."COUNTRIES" cascade constraints PURGE;
drop table "MARTYNIUKP"."DEPARTMENTS" cascade constraints PURGE;
drop table "MARTYNIUKP"."EMPLOYEES" cascade constraints PURGE;
drop table "MARTYNIUKP"."JOB_HISTORY" cascade constraints PURGE;
drop table "MARTYNIUKP"."JOB_GRADES" cascade constraints PURGE;
drop table "MARTYNIUKP"."JOBS" cascade constraints PURGE;
drop table "MARTYNIUKP"."LOCATIONS" cascade constraints PURGE;
drop table "MARTYNIUKP"."REGIONS" cascade constraints PURGE;


CREATE TABLE COUNTRIES AS (SELECT * FROM "HR"."COUNTRIES");
CREATE TABLE DEPARTMENTS AS (SELECT * FROM "HR"."DEPARTMENTS");
CREATE TABLE EMPLOYEES AS (SELECT * FROM "HR"."EMPLOYEES");
--CREATE TABLE JOB_GRADES AS (SELECT * FROM "HR"."JOB_GRADES");
CREATE TABLE JOB_HISTORY AS (SELECT * FROM "HR"."JOB_HISTORY");
CREATE TABLE JOBS AS (SELECT * FROM "HR"."JOBS");
CREATE TABLE LOCATIONS AS (SELECT * FROM "HR"."LOCATIONS");
CREATE TABLE REGIONS AS (SELECT * FROM "HR"."REGIONS");

ALTER TABLE REGIONS ADD PRIMARY KEY(REGION_ID);

ALTER TABLE COUNTRIES
    ADD PRIMARY KEY(COUNTRY_ID)
    ADD FOREIGN KEY(REGION_ID) REFERENCES REGIONS(REGION_ID);

ALTER TABLE LOCATIONS
    ADD PRIMARY KEY(LOCATION_ID)
    ADD FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID);

ALTER TABLE EMPLOYEES
    ADD PRIMARY KEY(EMPLOYEE_ID);

ALTER TABLE DEPARTMENTS
    ADD PRIMARY KEY(DEPARTMENT_ID)
    ADD FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
    ADD FOREIGN KEY(MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE JOBS
    ADD PRIMARY KEY(JOB_ID);

ALTER TABLE JOB_HISTORY
    ADD FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
    ADD FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
    ADD FOREIGN KEY(JOB_ID) REFERENCES JOBS(JOB_ID);

ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY(JOB_ID) REFERENCES JOBS(JOB_ID)
    ADD FOREIGN KEY(MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);


